namespace Paya.Automation.Editor.Converters
{
    using System;
    using System.Globalization;
    using System.Windows.Data;

    /// <summary>
    /// Specifies the <see cref="CultureDateConverter"/> class. 
    /// </summary>
    /// <seealso cref="System.Windows.Data.IValueConverter" />
    /// <autogeneratedoc />
    public sealed class CultureDateConverter : IValueConverter
    {
        #region Public Methods and Operators

        /// <summary>Converts the specified value.</summary>
        /// <param name="value">The value.</param>
        /// <param name="targetType">Type of the target.</param>
        /// <param name="parameter">The parameter.</param>
        /// <param name="culture">The culture.</param>
        /// <returns></returns>
        /// <autogeneratedoc />
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            if (value == null)
                return null;

            var dt = System.Convert.ToDateTime(value, culture);

            return dt.ToCultureString(culture, parameter != null ? System.Convert.ToString(parameter, culture) : null);
        }

        /// <summary>Converts the specified value back.</summary>
        /// <param name="value">The value.</param>
        /// <param name="targetType">Type of the target.</param>
        /// <param name="parameter">The parameter.</param>
        /// <param name="culture">The culture.</param>
        /// <returns></returns>
        /// <autogeneratedoc />
        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            return PersianUtility.ParsePersianDateTime(System.Convert.ToString(value, culture));
        }

        #endregion
    }
}
