using System;

namespace Paya.Automation.Editor.Updater
{
    using System.Threading.Tasks;
    using System.Windows;
    using MahApps.Metro.Controls.Dialogs;

    /// <summary>
    ///     Interaction logic for UpdateConfirmWindow.xaml
    /// </summary>
    [CLSCompliant(false)]
    public partial class UpdateConfirmWindow
    {
        #region Constructors and Destructors

        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateConfirmWindow"/> class.
        /// </summary>
        /// <autogeneratedoc />
        public UpdateConfirmWindow()
        {
            this.InitializeComponent();
        }

        #endregion

        #region Public Methods and Operators

        /// <summary>Shows the update confirm message asynchronous.</summary>
        /// <returns></returns>
        /// <autogeneratedoc />
        public async Task<bool> ShowUpdateConfirmMessageAsync()
        {
            this.Show();

            var res = await this.ShowMessageAsync("به روز رسانی", "ویرایشگر اتوماسیون اداری پندار نیاز به روز رسانی دارد. لطفا نامه‌های باز خود را ذخیره نموده و دکمه‌ی شروع به روز رسانی را کلیک کنید.", settings: new MetroDialogSettings { AffirmativeButtonText = "شروع به روز رسانی", ColorScheme = MetroDialogColorScheme.Inverted, AnimateShow = false, AnimateHide = false });
            return res == MessageDialogResult.Affirmative;
        }

        #endregion

        #region Methods

        private void TheUpdateConfirmWindow_Loaded(object sender, RoutedEventArgs e)
        {
        }

        #endregion
    }
}
