using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Windows.Markup;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.

[assembly: AssemblyTitle("Paya Automation Editor")]
[assembly: AssemblyDescription("The Rich Text Editor of Paya Office Automation")]

[assembly: System.Resources.NeutralResourcesLanguage("fa-IR")]

// The following GUID is for the ID of the typelib if this project is exposed to COM

[assembly: Guid("657f4324-4800-4312-b607-03e3b4419e8b")]

[assembly: ObfuscateAssembly(true)]

[assembly: InternalsVisibleTo(@"AutomationTest,PublicKey=002400000480000094000000060200000024000052534131000400000100010033111c4bdd91f43b7f3693b50bf787a1b13eb75bbd3bb52accc3084f9ad8ab64f087448e1f04247f445d2231a25b01cfe0a858749532a76f29980fa7bd0014ff9be3b3b721c468560d40c37c142e3b94b9cc6d0c17bb7a7e0c22940be869767715353da9f191eb320d6ea1652484d02ec67328056a3e95c30b827384add66fab")]

[assembly: AssemblyVersion("2.0.*")]

[assembly: XmlnsPrefix(Internal.DefaultNamespace, "paya")]
[assembly: XmlnsDefinition(Internal.DefaultNamespace, "Paya.Automation.Editor")]
[assembly: XmlnsDefinition(Internal.DefaultNamespace, "Paya.Automation.Editor.Behaviors")]
[assembly: XmlnsDefinition(Internal.DefaultNamespace, "Paya.Automation.Editor.Collections")]
[assembly: XmlnsDefinition(Internal.DefaultNamespace, "Paya.Automation.Editor.Converters")]
[assembly: XmlnsDefinition(Internal.DefaultNamespace, "Paya.Automation.Editor.Globalization")]
[assembly: XmlnsDefinition(Internal.DefaultNamespace, "Paya.Automation.Editor.Models")]
[assembly: XmlnsDefinition(Internal.DefaultNamespace, "Paya.Automation.Editor.PayaEditor")]
[assembly: XmlnsDefinition(Internal.DefaultNamespace, "Paya.Automation.Editor.StyleSelector")]

[module: SuppressMessage("ReSharper", "ConsiderUsingConfigureAwait")]

/// <summary>Specifies the <see cref="Internal" /> class.</summary>
/// <autogeneratedoc />
[SuppressMessage("ReSharper", "CheckNamespace")]
internal partial class Internal
{
    internal const string DefaultNamespace = "http://schemas.pss.ir/paya/automation/services/editor/";
}


