//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paya.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CalendarMonths {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CalendarMonths() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paya.Automation.Editor.Properties.CalendarMonths", typeof(CalendarMonths).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروردین.
        /// </summary>
        public static string Month1 {
            get {
                return ResourceManager.GetString("Month1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دی.
        /// </summary>
        public static string Month10 {
            get {
                return ResourceManager.GetString("Month10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بهمن.
        /// </summary>
        public static string Month11 {
            get {
                return ResourceManager.GetString("Month11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسفند.
        /// </summary>
        public static string Month12 {
            get {
                return ResourceManager.GetString("Month12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اردیبهشت.
        /// </summary>
        public static string Month2 {
            get {
                return ResourceManager.GetString("Month2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خرداد.
        /// </summary>
        public static string Month3 {
            get {
                return ResourceManager.GetString("Month3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تیر.
        /// </summary>
        public static string Month4 {
            get {
                return ResourceManager.GetString("Month4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرداد.
        /// </summary>
        public static string Month5 {
            get {
                return ResourceManager.GetString("Month5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهریور.
        /// </summary>
        public static string Month6 {
            get {
                return ResourceManager.GetString("Month6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهر.
        /// </summary>
        public static string Month7 {
            get {
                return ResourceManager.GetString("Month7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آبان.
        /// </summary>
        public static string Month8 {
            get {
                return ResourceManager.GetString("Month8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آذر.
        /// </summary>
        public static string Month9 {
            get {
                return ResourceManager.GetString("Month9", resourceCulture);
            }
        }
    }
}
