//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paya.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DateResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DateResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paya.Automation.Editor.Properties.DateResources", typeof(DateResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمعه.
        /// </summary>
        internal static string DayOfWeek_Friday {
            get {
                return ResourceManager.GetString("DayOfWeek_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوشنبه.
        /// </summary>
        internal static string DayOfWeek_Monday {
            get {
                return ResourceManager.GetString("DayOfWeek_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شنبه.
        /// </summary>
        internal static string DayOfWeek_Saturday {
            get {
                return ResourceManager.GetString("DayOfWeek_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکشنبه.
        /// </summary>
        internal static string DayOfWeek_Sunday {
            get {
                return ResourceManager.GetString("DayOfWeek_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنجشنبه.
        /// </summary>
        internal static string DayOfWeek_Thursday {
            get {
                return ResourceManager.GetString("DayOfWeek_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سه‌شنبه.
        /// </summary>
        internal static string DayOfWeek_Tuesday {
            get {
                return ResourceManager.GetString("DayOfWeek_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهارشنبه.
        /// </summary>
        internal static string DayOfWeek_Wednesday {
            get {
                return ResourceManager.GetString("DayOfWeek_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار ماه معتبر نیست.
        /// </summary>
        internal static string InvalidMonthValue {
            get {
                return ResourceManager.GetString("InvalidMonthValue", resourceCulture);
            }
        }
    }
}
