//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paya.Automation.Editor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paya.Automation.Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;access-policy&gt;
        ///	&lt;cross-domain-access&gt;
        ///		&lt;policy&gt;
        ///			&lt;allow-from http-request-headers=&quot;*&quot;&gt;
        ///				&lt;domain uri=&quot;http://*&quot; /&gt;
        ///
        ///				&lt;domain uri=&quot;https://*&quot; /&gt;
        ///
        ///				&lt;domain uri=&quot;*&quot; /&gt;
        ///			&lt;/allow-from&gt;
        ///			&lt;grant-to&gt;
        ///				&lt;resource path=&quot;/&quot; include-subpaths=&quot;true&quot; /&gt;
        ///			&lt;/grant-to&gt;
        ///		&lt;/policy&gt;
        ///	&lt;/cross-domain-access&gt;
        ///&lt;/access-policy&gt;.
        /// </summary>
        internal static string clientaccesspolicy {
            get {
                return ResourceManager.GetString("clientaccesspolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///
        ///&lt;!DOCTYPE cross-domain-policy SYSTEM &quot;http://www.macromedia.com/xml/dtds/cross-domain-policy.dtd&quot;&gt;
        ///&lt;cross-domain-policy&gt;
        ///	&lt;allow-http-request-headers-from domain=&quot;*&quot; headers=&quot;SOAPAction,Content-Type&quot; /&gt;
        ///&lt;/cross-domain-policy&gt;.
        /// </summary>
        internal static string crossdomain {
            get {
                return ResourceManager.GetString("crossdomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Favicon {
            get {
                object obj = ResourceManager.GetObject("Favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon_16_Fax {
            get {
                object obj = ResourceManager.GetObject("Icon_16_Fax", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing handler for mouse event flag: .
        /// </summary>
        internal static string MissingHandlerForMouseEventFlag {
            get {
                return ResourceManager.GetString("MissingHandlerForMouseEventFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای دسترسی. برای انجام این عمل، ابتدا از طریق مرورگر خود وارد سیستم شوید..
        /// </summary>
        internal static string NotAuthenticatedErrorMessage {
            get {
                return ResourceManager.GetString("NotAuthenticatedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایشگر پندار.
        /// </summary>
        internal static string PendarEditorTitle {
            get {
                return ResourceManager.GetString("PendarEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرستنده.
        /// </summary>
        internal static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of items per page must be positive..
        /// </summary>
        internal static string TheNumberOfItemsPerPageMustBePositive {
            get {
                return ResourceManager.GetString("TheNumberOfItemsPerPageMustBePositive", resourceCulture);
            }
        }
    }
}
